name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # Install dependencies in client folder
      - name: Install dependencies
        run: |
          cd client
          npm install

      # Build Vite app
      - name: Build Vite app
        run: |
          cd client
          npm run build

      # Clean unnecessary files to reduce file count
      - name: Clean build artifacts
        run: |
          cd client/dist
          # Remove source maps
          find . -name "*.map" -type f -delete
          # Remove hidden files (macOS, Windows)
          find . -name ".*" -type f -delete || echo "No hidden files to delete"

      # Install OIDC client for Azure deploy
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      # Get GitHub ID token
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      # Deploy prebuilt artifact to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ISLAND_0EC038D00 }}
          action: "upload"
          app_location: "./client"
          api_location: "" 
          output_location: "dist"
          skip_app_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
