# Docs: https://github.com/Azure/webapps-deploy

name: Deploy Node.js app to Azure Web App - NodeApplication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd server
          npm install

      # Optional: list files for debugging
      - name: List server folder contents
        run: |
          ls -R ./server

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NodeApplication'                # your Azure App Service name
          slot-name: 'Production'                     # change if you use a deployment slot
          package: ./server                            # path to your Node.js backend folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05F4A2455E894325AE5FB2035582BD2A }}
